# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_corredor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='alergias',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='medicamentos',
            field=models.TextField(max_length=150),
        ),
    ]
