# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170502_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='alergias',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='medicamentos',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
