# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170502_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='alergias',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='medicamentos',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
