# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tblcomuna_tblprovincia_tblregion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcomuna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblprovincia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblregion',
            options={'managed': False},
        ),
    ]
