# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170503_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='talla_polera',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=2),
        ),
    ]
