# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170504_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tiempo', models.CharField(max_length=20)),
                ('id_corredor', models.IntegerField()),
                ('categoria_id', models.IntegerField()),
                ('distancia_id', models.IntegerField()),
                ('team', models.CharField(max_length=20)),
                ('lugar_cat_dis', models.IntegerField()),
                ('lugar_gen', models.IntegerField()),
            ],
        ),
    ]
