# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
