# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170505_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancia',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
