# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_distancia_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
