# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170506_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
