# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_corredor_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='apellido_mat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='apellido_pat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='talla_polera',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=3, null=True),
        ),
    ]
