# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170506_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='tiempo',
            field=models.CharField(max_length=100),
        ),
    ]
