# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170506_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tiempo',
            field=models.CharField(max_length=50),
        ),
    ]
