# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170506_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='talla_polera',
            field=models.CharField(blank=True, choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=3, null=True),
        ),
    ]
